name: Release
on: [push]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml
      - name: Lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml
      - name: Test
        run: pnpm run test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml
      - name: Build
        run: pnpm run build

  release:
    needs: [build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
